# Generated by Django 2.2.7 on 2019-12-05 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funzione', models.CharField(choices=[('TE', 'Terapista'), ('PA', 'Padre'), ('MA', 'Madre'), ('SU', 'Supervisore'), ('DO', 'Dottore')], default='TE', max_length=2)),
                ('data_di_inzio', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialista',
                'verbose_name_plural': 'Specialisti',
            },
        ),
    ]
