# Generated by Django 2.2.7 on 2019-11-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persona',
        ),
    ]
