# Generated by Django 2.2.7 on 2019-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0002_auto_20191114_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
