# Generated by Django 2.2.7 on 2019-11-15 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persone', '0003_auto_20191114_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.CreateModel(
            name='Specialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funzione', models.CharField(choices=[('TE', 'Terapista'), ('PA', 'Padre'), ('MA', 'Madre'), ('SU', 'Supervisore'), ('DO', 'Dottore')], default='TE', max_length=2)),
                ('data_di_inzio', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialista',
                'verbose_name_plural': 'Specialisti',
            },
        ),
        migrations.CreateModel(
            name='Bambino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('data_di_nascita', models.DateField(blank=True, null=True)),
                ('data_di_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bambino',
                'verbose_name_plural': 'Bambini',
            },
        ),
    ]
