# Generated by Django 2.2.7 on 2019-11-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0004_auto_20191115_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bambino',
            name='creatore',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Bambino',
        ),
    ]
