# Generated by Django 2.2.7 on 2019-12-16 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tempi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteggioorario',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
