# Generated by Django 2.2.7 on 2020-01-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0003_auto_20191216_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_creazione',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
