# Generated by Django 2.2.7 on 2020-01-06 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0004_auto_20200106_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_creazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
