# Generated by Django 2.2.7 on 2019-12-04 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rapporti', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('domanda', models.CharField(blank=True, max_length=50)),
                ('specialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domanda',
                'verbose_name_plural': 'Domande',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=50)),
                ('obiettivo', models.CharField(blank=True, max_length=50)),
                ('procedura', models.CharField(blank=True, max_length=50)),
                ('attivo', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('specialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Prove',
            },
        ),
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('specialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programma',
                'verbose_name_plural': 'Programmi',
            },
        ),
        migrations.CreateModel(
            name='Esercizi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta', models.CharField(choices=[('NN', ''), ('C', 'C'), ('NC', 'NC'), ('PF', 'PF'), ('PI', 'PI')], max_length=2)),
                ('numero_di_volte', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmazione.Domande')),
                ('programma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmazione.Programma')),
                ('prova', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programmazione.Prova')),
                ('rinforzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rapporti.Rinforzo')),
            ],
            options={
                'verbose_name': 'Esercizio',
                'verbose_name_plural': 'Esercizi',
            },
        ),
    ]
