# Generated by Django 2.2.7 on 2019-12-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esercizi',
            name='domanda',
        ),
        migrations.AddField(
            model_name='esercizi',
            name='domanda',
            field=models.ManyToManyField(to='programmazione.Domande'),
        ),
        migrations.AlterField(
            model_name='esercizi',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmazione.Prova'),
        ),
        migrations.RemoveField(
            model_name='esercizi',
            name='rinforzo',
        ),
        migrations.AddField(
            model_name='esercizi',
            name='rinforzo',
            field=models.ManyToManyField(to='programmazione.Rinforzi'),
        ),
    ]
