# Generated by Django 2.2.7 on 2019-11-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenze',
            options={'verbose_name': 'Competenza', 'verbose_name_plural': 'Competenze'},
        ),
        migrations.AlterModelOptions(
            name='programma',
            options={'verbose_name': 'Programma', 'verbose_name_plural': 'Programmi'},
        ),
    ]
