# Generated by Django 2.2.7 on 2019-12-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esercizi',
            name='rinforzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rapporti.Rinforzi'),
        ),
    ]
