# Generated by Django 2.2.7 on 2019-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0002_prova_specialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='attivo',
            field=models.BooleanField(default=False),
        ),
    ]
