# Generated by Django 2.2.7 on 2019-12-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0002_auto_20191209_1549'),
        ('programmazione', '0002_auto_20191208_1403'),
    ]

    operations = [
    ]
