# Generated by Django 2.2.7 on 2019-11-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0003_prova_attivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programma',
            name='prove',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='programmazione.Prova'),
            preserve_default=False,
        ),
    ]
