# Generated by Django 2.2.7 on 2019-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0003_merge_20191209_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esercizi',
            name='numero_di_volte',
        ),
        migrations.AddField(
            model_name='esercizi',
            name='corretto',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizi',
            name='non_corretto',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizi',
            name='promt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizi',
            name='promt_fisico',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizi',
            name='promt_indicativo',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esercizi',
            name='risposta',
            field=models.CharField(choices=[('NN', ''), ('C', 'C'), ('NC', 'NC'), ('P', 'P'), ('PF', 'PF'), ('PI', 'PI')], max_length=2),
        ),
    ]
