# Generated by Django 2.2.7 on 2019-11-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0004_programma_prove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programma',
            name='prove',
        ),
        migrations.AddField(
            model_name='programma',
            name='prove',
            field=models.ManyToManyField(to='programmazione.Prova'),
        ),
    ]
