# Generated by Django 2.2.7 on 2019-11-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapporti', '0001_initial'),
        ('programmazione', '0005_auto_20191129_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programma',
            name='prove',
        ),
        migrations.RemoveField(
            model_name='programma',
            name='titolo',
        ),
        migrations.AddField(
            model_name='esercizi',
            name='rinforzo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Rapporti.Rinforzo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esercizi',
            name='domanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmazione.Domande'),
        ),
    ]
