# Generated by Django 2.2.7 on 2019-12-16 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0006_auto_20191209_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domande',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programma',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prova',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rinforzi',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
