# Generated by Django 2.2.7 on 2019-12-16 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chartitApp', '0002_creategraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategraph',
            name='fine',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creategraph',
            name='inizio',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 14, 10, 41, 10997, tzinfo=utc)),
        ),
    ]
