# Generated by Django 2.2.7 on 2019-12-16 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chartitApp', '0003_auto_20191216_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategraph',
            name='inizio',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 14, 15, 31, 567778, tzinfo=utc)),
        ),
    ]
