# Generated by Django 2.2.7 on 2019-12-16 14:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chartitApp', '0004_auto_20191216_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategraph',
            name='fine',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creategraph',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 14, 16, 12, 684826, tzinfo=utc)),
        ),
    ]
