# Generated by Django 2.2.7 on 2019-12-16 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programmazione', '0008_auto_20191216_1515'),
        ('chartitApp', '0005_auto_20191216_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategraph',
            name='prova',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmazione.Prova'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creategraph',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 20, 31, 28, 762242, tzinfo=utc)),
        ),
    ]
