# Generated by Django 2.2.7 on 2020-01-06 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chartitApp', '0017_auto_20200106_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategraph',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 14, 0, 18, 145059, tzinfo=utc)),
        ),
    ]
