# Generated by Django 2.2.7 on 2019-12-08 08:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapporti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relazioni',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
