# Generated by Django 2.2.7 on 2019-11-19 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rapporti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('relazione', models.TextField()),
                ('specialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relazione',
                'verbose_name_plural': 'Relazioni',
            },
        ),
    ]
