# Generated by Django 2.2.7 on 2019-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapporti', '0002_relazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableabc',
            name='antecedente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tableabc',
            name='conseguenza',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tableabc',
            name='funzione',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
