# Generated by Django 2.2.7 on 2019-12-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapporti', '0002_relazioni_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relazioni',
            old_name='content',
            new_name='feedback',
        ),
    ]
