# Generated by Django 2.2.7 on 2019-11-19 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rapporti', '0003_auto_20191119_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisiFunzionale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('antecedente', models.CharField(blank=True, max_length=500)),
                ('comportamento', models.CharField(max_length=500)),
                ('conseguenza', models.CharField(blank=True, max_length=500)),
                ('reazione', models.CharField(blank=True, max_length=500)),
                ('specialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidenti',
            },
        ),
        migrations.DeleteModel(
            name='TableABC',
        ),
    ]
