# Generated by Django 2.2.7 on 2019-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapporti', '0004_auto_20191208_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relazioni',
            name='feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
