# Generated by Django 2.2.7 on 2019-12-16 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rapporti', '0006_auto_20191216_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisifunzionali',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='relazioni',
            name='data_creazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
